name: Publish Docker images

on:
  release:
    types: [ released ]

jobs:
  push_to_registry:
    name: Push docker images to github container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Log in to github docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/romoshi/bot-manual-shop/bot-shop:${{ github.sha }}
            ghcr.io/romoshi/bot-manual-shop/bot-shop:latest
